#!/bin/bash

usage="$(basename "$0") [-h|-l] {load|unload|reload} servicename - service manager

where:
  -h  show this help text
  -l  list services"

die () {
  echo >&2 "$@"
  echo "$usage"
  exit 1
}

[ "$#" -ge 1 ] || die "1 argument required, $# provided"

while getopts ':hl' option; do
  case "$option" in
    l)
      find ~/Library/LaunchAgents/ -name 'homebrew*' -exec basename {} \; | sed 's/homebrew.mxcl.//' | sed 's/.plist//'
      exit
      ;;
    h | *)
      echo "$usage"
      exit
      ;;
  esac
done

SERVICE_SCRIPT=~/Library/LaunchAgents/homebrew.mxcl.$2.plist

if [ ! -f $SERVICE_SCRIPT ]; then
  echo "Service not found"
  exit 1
fi

AVAILABLE_COMMANDS="load unload reload"
command_exists=false
for command in $AVAILABLE_COMMANDS
do
  [[ $1 == $command ]] && command_exists=true
done

if [ $command_exists == false ] ; then
  echo "Command '$1' doesn't exist. Available commands: $AVAILABLE_COMMANDS"
  exit 1
fi

if [ $1 == "reload" ] ; then
  bruce unload $2
  bruce load $2
else
  echo $1ing $2...
  launchctl $1 -Fw $SERVICE_SCRIPT
  echo $2 $1ed.
fi
